services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fliqt
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    volumes:
      - minio-data:/data

  minio-setup:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (mc alias set myminio http://minio:9000 minioadmin minioadmin && mc ls myminio/fliqt || mc mb myminio/fliqt); do
        sleep 5;
      done"

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: migrate
    restart: on-failure
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=fliqt
      - DEBUG=true
      - PRETTY_LOGS=true
    depends_on:
      - mysql
    command: "./dist-migrate"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=fliqt
      - DEBUG=true
      - PRETTY_LOGS=true
      - TRACER_ENDPOINT=jaeger:4317
      - REDIS_URL=redis://redis:6379
      - S3_ENDPOINT=http://minio:9000
      - S3_BUCKET=fliqt
      - S3_KEY=minioadmin
      - S3_SECRET=minioadmin
    depends_on:
      - mysql
      - redis
      - minio
    command: "./dist-main"

  jaeger:
    image: jaegertracing/all-in-one:1.58
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"

volumes:
  minio-data:
  mysql-data:
  redis-data: